apiVersion: v1
kind: ConfigMap
metadata:
  name: django-variables
data:
  DJANGO_ENV: production
  DJANGO_DEBUG: "0"
  SECRET_KEY: )y^+8k$7c8l@wi-06^kl#4j=&0%*x_i4vrrnqb0u9r7uf8^04j
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_ADMIN_USER: admin
  DJANGO_ADMIN_EMAIL: "admin@example.com"
  DB_ENGINE: "django.db.backends.postgresql_psycopg2"
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: predictiondb
  DB_USER: postgres
  DATABASE: postgres